1 lgobfun_dv: (TC19) Equality test on reals is not reliable
2 lgobfun_dv: (TC19) Equality test on reals is not reliable
3 lgobfun_dv: (AD10) User help requested: constant nbdirsmax must hold the maximum number of differentiation directions
4 loggausspdf_dv: (TC19) Equality test on reals is not reliable
5 loggausspdf_dv: (AD10) User help requested: constant nbdirsmax must hold the maximum number of differentiation directions
